services:
  api:
    image: zasmlabs/crm-backend:v1.1
    ports:
      - "5000:8080"
    volumes:
      - C:/Data:/data
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/database
      - MACHINE_TYPE=local
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  db-data:


  default:
    driver: bridge